### ISSUE TITLE
How to send a downloadable link in mails?

### ISSUE THREAD

**Issue by Bajranghudda** [testfairy/testfairy-android-studio-plugin#10]
I have integrated test fairy uploader plug in - in Jenkins by helping this link -https://wiki.jenkins.io/display/JENKINS/TestFairy+Plugin 

And it succeed with success message, and I got **"download_page_url" - "url"**  with other keys...

I don't know how I can send this as an attachment (URL) to emails? 
Please suggest me anything.

**Comment by giltsl** [comment]
Hi @Bajranghudda please see [TestFairy Distribution Tutorial](https://youtu.be/Y2KpYgi8wLI). 
Or you can specify a testers group, so email will be sent to each tester whithin the group on each  upload as you can see at the [jenkins plugin documentation](https://wiki.jenkins.io/display/JENKINS/TestFairy+Plugin).

Please note that this ripo belong to testfairy-android-studio-plugin.
