### ISSUE TITLE
NoClassFoundExcepion

### ISSUE THREAD

**Issue by fmatosic** [testfairy/testfairy-android-studio-plugin#8]
After installing, added api key, pressed on the tf icon and got noClassFound exception.
Tried reinstalling but same error
![screen shot 2017-11-30 at 21 04 45](https://user-images.githubusercontent.com/3234580/33452361-4c01cf7a-d612-11e7-8b09-c23245b03f2b.png)
![screen shot 2017-11-30 at 21 04 54](https://user-images.githubusercontent.com/3234580/33452363-4e03777e-d612-11e7-905e-2611be0619f2.png)

**Comment by giltsl** [comment]
Was fixed at [Version 1.3](https://github.com/testfairy/testfairy-android-studio-plugin/releases/tag/1.3)
